set PROJECT=%1
set SOLUTION=%PROJECT%
set PROJECT_SOURCE=%SOURCE_ROOT%%PROJECT%
set INSTALL=%NATIVE_BUILD_ROOT%\binCS\%BUILD_TYPE%_out\%PROJECT%
devenv %PROJECT_SOURCE%\%SOLUTION%.sln /build "%BUILD_TYPE%"

