#VERSION: 1

create table `elec_sch5_session_info`(`session_id` char(36) NOT NULL,`hall_id` int(11) NULL,`charity_id` int(11) NULL,`board_size` int(11) NULL,`special` int(11) NULL,`max_cards` int(11) NULL,`max_bonanza` int(11) NULL,`last_bonanza` int(11) NULL,`bonus_size` int(11) NULL,`session_name` varchar(100) default '' NULL,UNIQUE KEY session_idkey (`session_id`),UNIQUE KEY session_namekey (`session_name`)) ENGINE=INNODB
create table `elec_sch5_session_macro_info`(`session_macro_id` char(36) NOT NULL,`session_macro_name` varchar(100) default '' NULL,UNIQUE KEY session_macro_idkey (`session_macro_id`),UNIQUE KEY session_macro_namekey (`session_macro_name`)) ENGINE=INNODB
create table `elec_sch5_session_macro_schedule`(`session_macro_schedule_id` char(36) NOT NULL,`starting_date` date NULL,`session_macro_id` char(36) NULL,UNIQUE KEY session_macro_schedule_idkey (`session_macro_schedule_id`),CONSTRAINT `elec_sch5_session_macro_on_day` FOREIGN KEY (`session_macro_id`)REFERENCES `elec_sch5_session_macro_info`(`session_macro_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_session_macro_session`(`session_macro_session_id` char(36) NOT NULL,`session_macro_id` char(36) NULL,`session_id` char(36) NULL,`session_number` int(11) NULL,`session_macro_session_name` varchar(100) default '' NULL,UNIQUE KEY session_macro_session_idkey (`session_macro_session_id`),CONSTRAINT `elec_sch5_session_macro_has_session` FOREIGN KEY (`session_macro_id`)REFERENCES `elec_sch5_session_macro_info`(`session_macro_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_in_session_macro` FOREIGN KEY (`session_id`)REFERENCES `elec_sch5_session_info`(`session_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_game_group_info`(`game_group_id` char(36) NOT NULL,`game_group_name` varchar(100) default '' NULL,UNIQUE KEY game_group_idkey (`game_group_id`),UNIQUE KEY game_group_namekey (`game_group_name`)) ENGINE=INNODB
create table `elec_sch5_game_info`(`hall_id` int(11) NULL,`charity_id` int(11) NULL,`game_id` char(36) NOT NULL,`game_name` varchar(100) default '' NULL,`game_type_id` int(11) NULL,`color_id` int(11) NULL,`special` tinyint(1) NULL,`poker` tinyint(1) NULL,UNIQUE KEY game_idkey (`game_id`),UNIQUE KEY game_namekey (`game_name`)) ENGINE=INNODB
create table `elec_sch5_pattern_description`(`pattern_id` char(36) NOT NULL,`hall_id` int(11) NULL,`charity_id` int(11) NULL,`pattern_name` varchar(100) default '' NULL,`number` int(11) NULL,`width` int(11) NULL,`height` int(11) NULL,`real_mode` int(11) NULL,`mode_mod` int(11) NULL,`board_size` int(11) NULL,`flags` int(11) NULL,`match` int(11) NULL,`count` int(11) NULL,`crazy_hardway` tinyint(1) NULL,UNIQUE KEY pattern_idkey (`pattern_id`),UNIQUE KEY pattern_namekey (`pattern_name`)) ENGINE=INNODB
create table `elec_sch5_pattern_data`(`pattern_data_id` char(36) NOT NULL,`pattern_id` char(36) NULL,`bits_int` int(11) NULL,`block` int(11) NULL,UNIQUE KEY pattern_data_idkey (`pattern_data_id`),CONSTRAINT `elec_sch5_pattern_has_bits` FOREIGN KEY (`pattern_id`)REFERENCES `elec_sch5_pattern_description`(`pattern_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_pattern_data_multi`(`pattern_data_multi_id` char(36) NOT NULL,`pattern_id` char(36) NULL,`member_pattern_id` int(11) NULL,`number` int(11) NULL,UNIQUE KEY pattern_data_multi_idkey (`pattern_data_multi_id`),CONSTRAINT `elec_sch5_pattern_has_sub_pattern` FOREIGN KEY (`pattern_id`)REFERENCES `elec_sch5_pattern_description`(`pattern_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_game_pattern`(`game_pattern_id` char(36) NOT NULL,`game_id` char(36) NULL,`pattern_id` char(36) NULL,`game_pattern_number` int(11) NULL,`remove_after` int(11) NULL,UNIQUE KEY game_pattern_idkey (`game_pattern_id`),UNIQUE `game_pattern_pair`(`game_id`,`pattern_id`),CONSTRAINT `elec_sch5_game_has_pattern` FOREIGN KEY (`game_id`)REFERENCES `elec_sch5_game_info`(`game_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_pattern_in_game` FOREIGN KEY (`pattern_id`)REFERENCES `elec_sch5_pattern_description`(`pattern_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_color_info`(`color_id` char(36) NOT NULL,`color_name` varchar(100) default '' NULL,`color` bigint NULL,`dat_id` int(11) NULL,UNIQUE KEY color_idkey (`color_id`),UNIQUE KEY color_namekey (`color_name`)) ENGINE=INNODB
create table `elec_sch5_pack_info`(`pack_id` char(36) NOT NULL,`hall_id` int(11) NULL,`charity_id` int(11) NULL,`pack_name` varchar(100) default '' NULL,`max_sell` int(11) NULL,`color_id` char(36) NULL,`price` int(11) NULL,`validation` int(11) NULL,`accrual_group_id` char(36) NULL,`onsize` int(11) NULL,`buy_in` int(11) NULL,`buy_in_level` int(11) NULL,`jumping_jackpot` int(11) NULL,`prize_level_id` int(11) NULL,`width` int(11) NULL,`height` int(11) NULL,`pages` int(11) NULL,`_3_number` tinyint(1) NULL,`double_action` tinyint(1) NULL,UNIQUE KEY pack_idkey (`pack_id`),UNIQUE KEY pack_namekey (`pack_name`),CONSTRAINT `elec_sch5_pack_is_color` FOREIGN KEY (`color_id`)REFERENCES `elec_sch5_color_info`(`color_id`)ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_bundle_info`(`bundle_id` char(36) NOT NULL,`bundle_name` varchar(100) default '' NULL,UNIQUE KEY bundle_idkey (`bundle_id`),UNIQUE KEY bundle_namekey (`bundle_name`)) ENGINE=INNODB
create table `elec_sch5_dealer`(`dealer_id` char(36) NOT NULL,`dealer_name` varchar(100) default '' NULL,`card_skip` int(11) NULL,`page_skip` int(11) NULL,`row_skip` int(11) NULL,`column_skip` int(11) NULL,`superstack` tinyint(1) NULL,UNIQUE KEY dealer_idkey (`dealer_id`),UNIQUE KEY dealer_namekey (`dealer_name`)) ENGINE=INNODB
create table `elec_sch5_dealer_history`(`dealer_history_id` char(36) NOT NULL,`dealer_id` char(36) NULL,`starting_card` int(11) NULL,`ending_card` int(11) NULL,`dealt_whenstamp` datetime NULL,UNIQUE KEY dealer_history_idkey (`dealer_history_id`),CONSTRAINT `elec_sch5_dealer_deals` FOREIGN KEY (`dealer_id`)REFERENCES `elec_sch5_dealer`(`dealer_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_cardset_info`(`cardset_id` char(36) NOT NULL,`name` varchar(100) default '' NULL,`friendly_name` varchar(100) default '' NULL,`cards` int(11) NULL,`manufacturer_id` varchar(100) default '' NULL,`machine_id` int(11) NULL,`machine_type_is_ccf` tinyint(1) NULL,UNIQUE KEY cardset_idkey (`cardset_id`)) ENGINE=INNODB
create table `elec_sch5_prize_level`(`prize_level_id` char(36) NOT NULL,`prize_level_name` varchar(100) default '' NULL,`str_color` varchar(100) default '' NULL,UNIQUE KEY prize_level_idkey (`prize_level_id`),UNIQUE KEY prize_level_namekey (`prize_level_name`)) ENGINE=INNODB
create table `elec_sch5_cardset_ranges`(`cardset_range_id` char(36) NOT NULL,`cardset_range_name` varchar(100) default '' NULL,`cardset_id` char(36) NULL,`prize_level_id` char(36) NULL,`start` int(11) NULL,`end` int(11) NULL,`base` int(11) NULL,`offset` int(11) NULL,`electronic` tinyint(1) NULL,`barcode_paper` tinyint(1) NULL,`dealer_id` char(36) NULL,`sales_database` varchar(64) default '' NULL,UNIQUE KEY cardset_range_idkey (`cardset_range_id`),UNIQUE KEY cardset_range_namekey (`cardset_range_name`),CONSTRAINT `elec_sch5_cardset_has_cardset_range` FOREIGN KEY (`cardset_id`)REFERENCES `elec_sch5_cardset_info`(`cardset_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_cardset_range_has_dealer` FOREIGN KEY (`dealer_id`)REFERENCES `elec_sch5_dealer`(`dealer_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_pack_cardset_range`(`pack_cardset_range_id` char(36) NOT NULL,`pack_id` char(36) NULL,`cardset_range_id` char(36) NULL,`pack_cardset_range_number` int(11) NULL,UNIQUE KEY pack_cardset_range_idkey (`pack_cardset_range_id`),CONSTRAINT `elec_sch5_pack_has_cardset_range` FOREIGN KEY (`pack_id`)REFERENCES `elec_sch5_pack_info`(`pack_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_cardset_range_in_pack` FOREIGN KEY (`cardset_range_id`)REFERENCES `elec_sch5_cardset_ranges`(`cardset_range_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_game_group_game`(`game_group_game_id` char(36) NOT NULL,`game_group_id` char(36) NULL,`game_id` char(36) NULL,`game_number` int(11) NULL,UNIQUE KEY game_group_game_idkey (`game_group_game_id`),CONSTRAINT `elec_sch5_game_group_has_game` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_game_in_game_group` FOREIGN KEY (`game_id`)REFERENCES `elec_sch5_game_info`(`game_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_game_group_prize_level`(`game_group_prize_level_id` char(36) NOT NULL,`game_group_id` char(36) NULL,`prize_level_id` char(36) NULL,`prize_level_number` int(11) NULL,UNIQUE KEY game_group_prize_level_idkey (`game_group_prize_level_id`),CONSTRAINT `elec_sch5_game_group_has_prize_level` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_prize_level_in_game_group` FOREIGN KEY (`prize_level_id`)REFERENCES `elec_sch5_prize_level`(`prize_level_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_game_group_pack`(`game_group_pack_id` char(36) NOT NULL,`game_group_id` char(36) NULL,`pack_id` char(36) NULL,`game_group_pack_number` int(11) NULL,UNIQUE KEY game_group_pack_idkey (`game_group_pack_id`),CONSTRAINT `elec_sch5_game_group_has_pack` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_pack_in_game_group` FOREIGN KEY (`pack_id`)REFERENCES `elec_sch5_pack_info`(`pack_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_session_game`(`session_game_id` char(36) NOT NULL,`session_id` char(36) NULL,`game_id` char(36) NULL,`game_number` int(11) NULL,`ball_timer` int(11) NULL,`progressive` tinyint(1) NULL,`bonanza` tinyint(1) NULL,`wild` tinyint(1) NULL,`double_wild` tinyint(1) NULL,`blind` tinyint(1) NULL,`single_hotball` tinyint(1) NULL,`color_id` char(36) NULL,UNIQUE KEY session_game_idkey (`session_game_id`)) ENGINE=INNODB
create table `elec_sch5_session_bundle`(`session_bundle_id` char(36) NOT NULL,`session_id` char(36) NULL,`bundle_id` char(36) NULL,`bundle_number` int(11) NULL,UNIQUE KEY session_bundle_idkey (`session_bundle_id`),CONSTRAINT `elec_sch5_session_has_bundle` FOREIGN KEY (`session_id`)REFERENCES `elec_sch5_session_info`(`session_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_bundle_in_session` FOREIGN KEY (`bundle_id`)REFERENCES `elec_sch5_bundle_info`(`bundle_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_bundle_pack`(`bundle_pack_id` char(36) NOT NULL,`bundle_id` char(36) NULL,`pack_id` char(36) NULL,`pack_number` int(11) NULL,UNIQUE KEY bundle_pack_idkey (`bundle_pack_id`),CONSTRAINT `elec_sch5_bundle_has_pack` FOREIGN KEY (`bundle_id`)REFERENCES `elec_sch5_bundle_info`(`bundle_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_pack_in_bundle` FOREIGN KEY (`pack_id`)REFERENCES `elec_sch5_pack_info`(`pack_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_session_game_group`(`session_game_group_id` char(36) NOT NULL,`session_id` char(36) NULL,`game_group_id` char(36) NULL,`game_number` int(11) NULL,UNIQUE KEY session_game_group_idkey (`session_game_group_id`),CONSTRAINT `elec_sch5_session_has_game_group` FOREIGN KEY (`session_id`)REFERENCES `elec_sch5_session_info`(`session_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_game_group_in_session` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_session_game_group_game`(`session_id` char(36) NULL,`session_game_group_id` char(36) NULL,`game_group_id` char(36) NULL,`game_group_game_id` char(36) NULL,`game_id` char(36) NULL,`session_game_group_game_id` char(36) NOT NULL,`game_number` int(11) NULL,`ball_timer` int(11) NULL,`overlap_prior` tinyint(1) NULL,`progressive` tinyint(1) NULL,`bonanza` tinyint(1) NULL,`wild` tinyint(1) NULL,`double_wild` tinyint(1) NULL,`blind` tinyint(1) NULL,`single_hotball` tinyint(1) NULL,`color_id` char(36) NULL,UNIQUE KEY session_game_group_game_idkey (`session_game_group_game_id`),CONSTRAINT `elec_sch5_session_game_group_game_meta_session_info` FOREIGN KEY (`session_id`)REFERENCES `elec_sch5_session_info`(`session_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_game_group_game_meta_session_game_group` FOREIGN KEY (`session_game_group_id`)REFERENCES `elec_sch5_session_game_group`(`session_game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_game_group_game_meta_game_group_info` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_game_group_game_meta_game_group_game` FOREIGN KEY (`game_group_game_id`)REFERENCES `elec_sch5_game_group_game`(`game_group_game_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_game_group_game_meta_game_info` FOREIGN KEY (`game_id`)REFERENCES `elec_sch5_game_info`(`game_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_game_group_game_is_color` FOREIGN KEY (`color_id`)REFERENCES `elec_sch5_color_info`(`color_id`)ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_pack_face_prize_level`(`pack_face_prize_level_id` char(36) NOT NULL,`pack_id` char(36) NULL,`prize_level_id` char(36) NULL,`pack_face_prize_level_number` int(11) NULL,`color` varchar(100) default '' NULL,`face` int(11) NULL,UNIQUE KEY pack_face_prize_level_idkey (`pack_face_prize_level_id`),CONSTRAINT `elec_sch5_pack_has_prize_level` FOREIGN KEY (`pack_id`)REFERENCES `elec_sch5_pack_info`(`pack_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_prize_level_in_pack` FOREIGN KEY (`prize_level_id`)REFERENCES `elec_sch5_prize_level`(`prize_level_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_scheduled_prizes`(`session_id` char(36) NULL,`session_game_group_game_id` char(36) NULL,`game_group_id` char(36) NULL,`game_group_prize_level_id` char(36) NULL,`scheduled_prize_id` char(36) NOT NULL,UNIQUE KEY scheduled_prize_idkey (`scheduled_prize_id`)) ENGINE=INNODB
create table `elec_sch5_prize_schedule`(`prize_schedule_id` char(36) NOT NULL,`prize_level_id` char(36) NULL,`session_macro_id` char(36) NULL,`session_id` char(36) NULL,`session_game_group_game_id` char(36) NULL,`session_number` int(11) NULL,`amount` int(11) NULL,UNIQUE KEY prize_schedule_idkey (`prize_schedule_id`),UNIQUE `prizekey`(`session_game_group_game_id`,`prize_level_id`,`session_macro_id`,`session_number`)) ENGINE=INNODB
create table `elec_sch5_prize_schedule_override`(`prize_schedule_id` char(36) NULL,`day_of_week` int(11) NULL,`specific_date` date NULL,`new_amount` int(11) NULL,UNIQUE `prizekey`(`prize_schedule_id`,`day_of_week`,`specific_date`),CONSTRAINT `elec_sch5_prize_override` FOREIGN KEY (`prize_schedule_id`)REFERENCES `elec_sch5_prize_schedule`(`prize_schedule_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_prize_schedule2`(`prize_schedule2_id` char(36) NOT NULL,`prize_level_id` char(36) NULL,`session_macro_id` char(36) NULL,`session_id` char(36) NULL,`session_game_group_game_id` char(36) NULL,`amount` int(11) NULL,UNIQUE KEY prize_schedule2_idkey (`prize_schedule2_id`),CONSTRAINT `elec_sch5_game_prizes` FOREIGN KEY (`session_game_group_game_id`)REFERENCES `elec_sch5_session_game_group_game`(`session_game_group_game_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_prize_schedule_session_override`(`prize_schedule_session_override_id` char(36) NOT NULL,`prize_schedule2_id` char(36) NULL,`session_number` int(11) NULL,`amount` int(11) NULL,UNIQUE KEY prize_schedule_session_override_idkey (`prize_schedule_session_override_id`),CONSTRAINT `elec_sch5_session_prize_override` FOREIGN KEY (`prize_schedule2_id`)REFERENCES `elec_sch5_prize_schedule2`(`prize_schedule2_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_prize_schedule_date_override`(`prize_schedule2_id` char(36) NULL,`prize_schedule_session_override_id` char(36) NULL,`specific_date` date NULL,`amount` int(11) NULL,CONSTRAINT `elec_sch5_day_prize_override` FOREIGN KEY (`prize_schedule2_id`)REFERENCES `elec_sch5_prize_schedule2`(`prize_schedule2_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_day_prize_override` FOREIGN KEY (`prize_schedule_session_override_id`)REFERENCES `elec_sch5_prize_schedule_session_override`(`prize_schedule_session_override_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_prize_schedule_day_class_override`(`prize_schedule2_id` char(36) NULL,`prize_schedule_session_override_id` char(36) NULL,`day_class` int(11) NULL,`amount` int(11) NULL,CONSTRAINT `elec_sch5_day_class_prize_override` FOREIGN KEY (`prize_schedule2_id`)REFERENCES `elec_sch5_prize_schedule2`(`prize_schedule2_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_day_class_prize_override` FOREIGN KEY (`prize_schedule_session_override_id`)REFERENCES `elec_sch5_prize_schedule_session_override`(`prize_schedule_session_override_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_prize_schedule_day_type_override`(`prize_schedule2_id` char(36) NULL,`prize_schedule_session_override_id` char(36) NULL,`day_of_week` int(11) NULL,`amount` int(11) NULL,CONSTRAINT `elec_sch5_day_type_prize_override` FOREIGN KEY (`prize_schedule2_id`)REFERENCES `elec_sch5_prize_schedule2`(`prize_schedule2_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_day_type_prize_override` FOREIGN KEY (`prize_schedule_session_override_id`)REFERENCES `elec_sch5_prize_schedule_session_override`(`prize_schedule_session_override_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_price_schedule`(`price_schedule_id` char(36) NOT NULL,`session_macro_id` int(11) NULL,`session_number` int(11) NULL,`session_id` int(11) NULL,`session_game_group_game_id` int(11) NULL,`amount` int(11) NULL,UNIQUE KEY price_schedule_idkey (`price_schedule_id`),UNIQUE `pricekey`(`session_game_group_game_id`,`session_macro_id`,`session_number`)) ENGINE=INNODB
create table `elec_sch5_price_schedule_override`(`price_schedule_id` int(11) NULL,`day_of_week` int(11) NULL,`specific_date` date NULL,`new_amount` int(11) NULL,UNIQUE `pricekey`(`price_schedule_id`,`day_of_week`,`specific_date`)) ENGINE=INNODB
create table `elec_sch5_session_pack`(`session_id` char(36) NULL,`session_game_group_id` char(36) NULL,`game_group_id` char(36) NULL,`game_group_pack_id` char(36) NULL,`pack_id` char(36) NULL,`session_pack_id` char(36) NOT NULL,`Name` varchar(100) default '' NULL,`pack_number` int(11) NULL,UNIQUE KEY session_pack_idkey (`session_pack_id`),CONSTRAINT `elec_sch5_session_pack_meta_session_info` FOREIGN KEY (`session_id`)REFERENCES `elec_sch5_session_info`(`session_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_pack_meta_session_game_group` FOREIGN KEY (`session_game_group_id`)REFERENCES `elec_sch5_session_game_group`(`session_game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_pack_meta_game_group_info` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_pack_meta_game_group_pack` FOREIGN KEY (`game_group_pack_id`)REFERENCES `elec_sch5_game_group_pack`(`game_group_pack_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_pack_meta_pack_info` FOREIGN KEY (`pack_id`)REFERENCES `elec_sch5_pack_info`(`pack_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB
create table `elec_sch5_session_prize`(`session_id` char(36) NULL,`session_game_group_id` char(36) NULL,`game_group_id` char(36) NULL,`game_group_prize_level_id` char(36) NULL,`prize_level_id` char(36) NULL,`session_prize_id` char(36) NOT NULL,`Name` varchar(100) default '' NULL,`prize_number` int(11) NULL,UNIQUE KEY session_prize_idkey (`session_prize_id`),CONSTRAINT `elec_sch5_session_prize_meta_session_info` FOREIGN KEY (`session_id`)REFERENCES `elec_sch5_session_info`(`session_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_prize_meta_session_game_group` FOREIGN KEY (`session_game_group_id`)REFERENCES `elec_sch5_session_game_group`(`session_game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_prize_meta_game_group_info` FOREIGN KEY (`game_group_id`)REFERENCES `elec_sch5_game_group_info`(`game_group_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_prize_meta_game_group_prize_level` FOREIGN KEY (`game_group_prize_level_id`)REFERENCES `elec_sch5_game_group_prize_level`(`game_group_prize_level_id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `elec_sch5_session_prize_meta_prize_level` FOREIGN KEY (`prize_level_id`)REFERENCES `elec_sch5_prize_level`(`prize_level_id`)ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=INNODB



#VERSION: 2

