//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	public class NxControllerShapeHit : DoxyBindObject
	{
		
		internal NxControllerShapeHit(IntPtr ptr) : 
				base(ptr)
		{
		}
		
		/// <summary>Current controller. </summary>
		public NxController controller
		{
			get
			{
				return NxController.GetClass(get_NxControllerShapeHit_controller_INVOKE(ClassPointer));
			}
			set
			{
				set_NxControllerShapeHit_controller_INVOKE(ClassPointer, value.ClassPointer);
			}
		}
		
		/// <summary>Touched shape. </summary>
		public NxShape shape
		{
			get
			{
				return NxShape.GetClass(get_NxControllerShapeHit_shape_INVOKE(ClassPointer));
			}
			set
			{
				set_NxControllerShapeHit_shape_INVOKE(ClassPointer, value.ClassPointer);
			}
		}
		
		/// <summary>Contact position in world space. </summary>
		public NxExtendedVec3 worldPos
		{
			get
			{
				NxExtendedVec3 value = get_NxControllerShapeHit_worldPos_INVOKE(ClassPointer);
				return value;
			}
			set
			{
				set_NxControllerShapeHit_worldPos_INVOKE(ClassPointer, value);
			}
		}
		
		/// <summary>Contact normal in world space. </summary>
		public NxVec3 worldNormal
		{
			get
			{
				NxVec3 value = get_NxControllerShapeHit_worldNormal_INVOKE(ClassPointer);
				return value;
			}
			set
			{
				set_NxControllerShapeHit_worldNormal_INVOKE(ClassPointer, value);
			}
		}
		
		/// <summary>Reserved for future use. </summary>
		public uint id
		{
			get
			{
				uint value = get_NxControllerShapeHit_id_INVOKE(ClassPointer);
				return value;
			}
			set
			{
				set_NxControllerShapeHit_id_INVOKE(ClassPointer, value);
			}
		}
		
		/// <summary>Motion direction. </summary>
		public NxVec3 dir
		{
			get
			{
				NxVec3 value = get_NxControllerShapeHit_dir_INVOKE(ClassPointer);
				return value;
			}
			set
			{
				set_NxControllerShapeHit_dir_INVOKE(ClassPointer, value);
			}
		}
		
		/// <summary>Motion length. </summary>
		public float length
		{
			get
			{
				float value = get_NxControllerShapeHit_length_INVOKE(ClassPointer);
				return value;
			}
			set
			{
				set_NxControllerShapeHit_length_INVOKE(ClassPointer, value);
			}
		}
		
		#region Imports
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_controller")]
        private extern static void set_NxControllerShapeHit_controller_INVOKE (HandleRef classPointer, HandleRef newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_controller")]
        private extern static IntPtr get_NxControllerShapeHit_controller_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_shape")]
        private extern static void set_NxControllerShapeHit_shape_INVOKE (HandleRef classPointer, HandleRef newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_shape")]
        private extern static IntPtr get_NxControllerShapeHit_shape_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_worldPos")]
        private extern static void set_NxControllerShapeHit_worldPos_INVOKE (HandleRef classPointer, NxExtendedVec3 newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_worldPos")]
        private extern static NxExtendedVec3 get_NxControllerShapeHit_worldPos_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_worldNormal")]
        private extern static void set_NxControllerShapeHit_worldNormal_INVOKE (HandleRef classPointer, NxVec3 newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_worldNormal")]
        private extern static NxVec3 get_NxControllerShapeHit_worldNormal_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_id")]
        private extern static void set_NxControllerShapeHit_id_INVOKE (HandleRef classPointer, System.UInt32 newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_id")]
        private extern static System.UInt32 get_NxControllerShapeHit_id_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_dir")]
        private extern static void set_NxControllerShapeHit_dir_INVOKE (HandleRef classPointer, NxVec3 newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_dir")]
        private extern static NxVec3 get_NxControllerShapeHit_dir_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxControllerShapeHit_length")]
        private extern static void set_NxControllerShapeHit_length_INVOKE (HandleRef classPointer, System.Single newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxControllerShapeHit_length")]
        private extern static System.Single get_NxControllerShapeHit_length_INVOKE (HandleRef classPointer);

		#endregion
		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="new_NxControllerShapeHit")]
        private extern static IntPtr new_NxControllerShapeHit_INVOKE (bool do_override);

		
		public NxControllerShapeHit() : 
				base(new_NxControllerShapeHit_INVOKE(false))
		{
			GC.ReRegisterForFinalize(this);
		}
		
		private static System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference> database = new System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference>();
		
		protected override void SetPointer(IntPtr ptr)
		{
			base.SetPointer(ptr);
			database[ptr] = new WeakReference(this);
		}
		
		public override void Dispose()
		{
			database.Remove(ClassPointer.Handle);
			base.Dispose();
		}
		
		public static NxControllerShapeHit GetClass(IntPtr ptr)
		{
			if ((ptr == IntPtr.Zero))
			{
				return null;
			}
			System.WeakReference obj;
			if (database.TryGetValue(ptr, out obj))
			{
				if (obj.IsAlive)
				{
					return ((NxControllerShapeHit)(obj.Target));
				}
			}
			return new NxControllerShapeHit(ptr);
		}
		
		protected override System.Collections.Generic.List<System.IntPtr> CreateFunctionPointers()
		{
			System.Collections.Generic.List<System.IntPtr> list = base.CreateFunctionPointers();
			return list;
		}
	}
}
