//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	[System.Flags()]
	public enum NxCompartmentType : uint
	{
		
NX_SCT_RIGIDBODY =  0,
		
NX_SCT_FLUID =  1,
		
NX_SCT_CLOTH =  2,
		
NX_SCT_SOFTBODY =  2,
	}
}
