//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	[System.Flags()]
	public enum NxErrorCode : uint
	{
		
NXE_NO_ERROR =  0,
		
NXE_INVALID_PARAMETER =  1,
		
NXE_INVALID_OPERATION =  2,
		
NXE_OUT_OF_MEMORY =  3,
		
NXE_INTERNAL_ERROR =  4,
		
NXE_ASSERTION =  107,
		
NXE_DB_INFO =  205,
		
NXE_DB_WARNING =  206,
		
NXE_DB_PRINT =  208,
	}
}
