//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	[System.Flags()]
	public enum NxFluidFlag : uint
	{
		
NX_FF_VISUALIZATION =  (1<<0),
		
NX_FF_DISABLE_GRAVITY =  (1<<1),
		
NX_FF_COLLISION_TWOWAY =  (1<<2),
		
NX_FF_ENABLED =  (1<<3),
		
NX_FF_HARDWARE =  (1<<4),
		
NX_FF_PRIORITY_MODE =  (1<<5),
		
NX_FF_PROJECT_TO_PLANE =  (1<<6),
		
NX_FF_FORCE_STRICT_COOKING_FORMAT =  (1<<7),
	}
}
