//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	public class NxInterfaceStats : NxInterface
	{
		
		internal NxInterfaceStats(IntPtr ptr) : 
				base(ptr)
		{
		}
		
		/// <summary></summary>
		public override int getVersionNumber()
		{
			return NxInterfaceStats_getVersionNumber_INVOKE(ClassPointer, doSetFunctionPointers);
		}
		
		private int getVersionNumber_virtual()
		{
			return getVersionNumber();
		}
		
		delegate int getVersionNumber_0_delegate();
		
		
		
		
		
		
		private getVersionNumber_0_delegate getVersionNumber_0_delegatefield;
		
		/// <summary></summary>
		public override NxInterfaceType getInterfaceType()
		{
			return NxInterfaceStats_getInterfaceType_INVOKE(ClassPointer, doSetFunctionPointers);
		}
		
		private NxInterfaceType getInterfaceType_virtual()
		{
			return getInterfaceType();
		}
		
		delegate NxInterfaceType getInterfaceType_1_delegate();
		
		
		
		
		
		
		private getInterfaceType_1_delegate getInterfaceType_1_delegatefield;
		
		/// <summary></summary>
		public virtual bool getHeapSize(ref int used, ref int unused)
		{
			if (doSetFunctionPointers)
			{
				throw new System.NotSupportedException("Cannot call abstract base member");
			}
			return NxInterfaceStats_getHeapSize_INVOKE(ClassPointer, doSetFunctionPointers, ref used, ref unused);
		}
		
		private bool getHeapSize_virtual([In()] [Out()] ref int used, [In()] [Out()] ref int unused)
		{
			return getHeapSize(ref used, ref unused);
		}
		
		delegate bool getHeapSize_2_delegate([In()] [Out()] ref int used, [In()] [Out()] ref int unused);
		
		
		
		
		
		
		private getHeapSize_2_delegate getHeapSize_2_delegatefield;
		
		#region Imports
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxInterfaceStats_getVersionNumber")]
        private extern static System.Int32 NxInterfaceStats_getVersionNumber_INVOKE (HandleRef classPointer, System.Boolean call_explicit);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxInterfaceStats_getInterfaceType")]
        private extern static NxInterfaceType NxInterfaceStats_getInterfaceType_INVOKE (HandleRef classPointer, System.Boolean call_explicit);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxInterfaceStats_getHeapSize")]
        private extern static System.Boolean NxInterfaceStats_getHeapSize_INVOKE (HandleRef classPointer, System.Boolean call_explicit, [In()] [Out()] ref System.Int32 used, [In()] [Out()] ref System.Int32 unused);

		#endregion
		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="new_NxInterfaceStats")]
        private extern static IntPtr new_NxInterfaceStats_INVOKE (bool do_override);

		
		protected NxInterfaceStats() : 
				base(IntPtr.Zero)
		{
			GC.ReRegisterForFinalize(this);
			if ((GetType() != typeof(NxInterfaceStats)))
			{
				doSetFunctionPointers = true;
				SetPointer(new_NxInterfaceStats_INVOKE(doSetFunctionPointers));
				System.IntPtr[] pointers = CreateFunctionPointers().ToArray();
				set_pointers_INVOKE(ClassPointer, pointers, pointers.Length);
			}
			else
			{
				SetPointer(new_NxInterfaceStats_INVOKE(doSetFunctionPointers));
			}
		}
		
		private static System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference> database = new System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference>();
		
		protected override void SetPointer(IntPtr ptr)
		{
			base.SetPointer(ptr);
			database[ptr] = new WeakReference(this);
		}
		
		public override void Dispose()
		{
			database.Remove(ClassPointer.Handle);
			base.Dispose();
		}
		
		public static NxInterfaceStats GetClass(IntPtr ptr)
		{
			if ((ptr == IntPtr.Zero))
			{
				return null;
			}
			System.WeakReference obj;
			if (database.TryGetValue(ptr, out obj))
			{
				if (obj.IsAlive)
				{
					return ((NxInterfaceStats)(obj.Target));
				}
			}
			return new NxInterfaceStats(ptr);
		}
		
		protected override System.Collections.Generic.List<System.IntPtr> CreateFunctionPointers()
		{
			System.Collections.Generic.List<System.IntPtr> list = base.CreateFunctionPointers();
			getVersionNumber_0_delegatefield = new getVersionNumber_0_delegate(this.getVersionNumber_virtual);
			list.Add(Marshal.GetFunctionPointerForDelegate(getVersionNumber_0_delegatefield));
			getInterfaceType_1_delegatefield = new getInterfaceType_1_delegate(this.getInterfaceType_virtual);
			list.Add(Marshal.GetFunctionPointerForDelegate(getInterfaceType_1_delegatefield));
			getHeapSize_2_delegatefield = new getHeapSize_2_delegate(this.getHeapSize_virtual);
			list.Add(Marshal.GetFunctionPointerForDelegate(getHeapSize_2_delegatefield));
			return list;
		}
	}
}
