//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	[System.Flags()]
	public enum NxJointType : uint
	{
		
NX_JOINT_PRISMATIC,
		
NX_JOINT_REVOLUTE,
		
NX_JOINT_CYLINDRICAL,
		
NX_JOINT_SPHERICAL,
		
NX_JOINT_POINT_ON_LINE,
		
NX_JOINT_POINT_IN_PLANE,
		
NX_JOINT_DISTANCE,
		
NX_JOINT_PULLEY,
		
NX_JOINT_FIXED,
		
NX_JOINT_D6,
		
NX_JOINT_COUNT,
		
NX_JOINT_FORCE_DWORD =  0x7fffffff,
	}
}
