//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	public class NxJointLimitSoftPairDesc : DoxyBindObject
	{
		
		internal NxJointLimitSoftPairDesc(IntPtr ptr) : 
				base(ptr)
		{
		}
		
		/// <summary>The low limit (smaller value). </summary>
		public NxJointLimitSoftDesc low
		{
			get
			{
				return NxJointLimitSoftDesc.GetClass(get_NxJointLimitSoftPairDesc_low_INVOKE(ClassPointer));
			}
			set
			{
				set_NxJointLimitSoftPairDesc_low_INVOKE(ClassPointer, value.ClassPointer);
			}
		}
		
		/// <summary>the high limit (larger value) </summary>
		public NxJointLimitSoftDesc high
		{
			get
			{
				return NxJointLimitSoftDesc.GetClass(get_NxJointLimitSoftPairDesc_high_INVOKE(ClassPointer));
			}
			set
			{
				set_NxJointLimitSoftPairDesc_high_INVOKE(ClassPointer, value.ClassPointer);
			}
		}
		
		/// <summary>Constructor, sets members to default values. </summary>
		public NxJointLimitSoftPairDesc() : 
				base(new_NxJointLimitSoftPairDesc_INVOKE(false))
		{
			GC.ReRegisterForFinalize(this);
		}
		
		/// <summary>Sets members to default values. </summary>
		public void setToDefault()
		{
			NxJointLimitSoftPairDesc_setToDefault_INVOKE(ClassPointer, doSetFunctionPointers);
		}
		
		/// <summary>Returns true if the descriptor is valid. </summary>
		public bool isValid()
		{
			return NxJointLimitSoftPairDesc_isValid_INVOKE(ClassPointer, doSetFunctionPointers);
		}
		
		#region Imports
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxJointLimitSoftPairDesc_low")]
        private extern static void set_NxJointLimitSoftPairDesc_low_INVOKE (HandleRef classPointer, HandleRef newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxJointLimitSoftPairDesc_low")]
        private extern static IntPtr get_NxJointLimitSoftPairDesc_low_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="set_NxJointLimitSoftPairDesc_high")]
        private extern static void set_NxJointLimitSoftPairDesc_high_INVOKE (HandleRef classPointer, HandleRef newvalue);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="get_NxJointLimitSoftPairDesc_high")]
        private extern static IntPtr get_NxJointLimitSoftPairDesc_high_INVOKE (HandleRef classPointer);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="new_NxJointLimitSoftPairDesc")]
        private extern static IntPtr new_NxJointLimitSoftPairDesc_INVOKE (System.Boolean do_override);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxJointLimitSoftPairDesc_setToDefault")]
        private extern static void NxJointLimitSoftPairDesc_setToDefault_INVOKE (HandleRef classPointer, System.Boolean call_explicit);

		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxJointLimitSoftPairDesc_isValid")]
        private extern static System.Boolean NxJointLimitSoftPairDesc_isValid_INVOKE (HandleRef classPointer, System.Boolean call_explicit);

		#endregion
		
		private static System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference> database = new System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference>();
		
		protected override void SetPointer(IntPtr ptr)
		{
			base.SetPointer(ptr);
			database[ptr] = new WeakReference(this);
		}
		
		public override void Dispose()
		{
			database.Remove(ClassPointer.Handle);
			base.Dispose();
		}
		
		public static NxJointLimitSoftPairDesc GetClass(IntPtr ptr)
		{
			if ((ptr == IntPtr.Zero))
			{
				return null;
			}
			System.WeakReference obj;
			if (database.TryGetValue(ptr, out obj))
			{
				if (obj.IsAlive)
				{
					return ((NxJointLimitSoftPairDesc)(obj.Target));
				}
			}
			return new NxJointLimitSoftPairDesc(ptr);
		}
		
		protected override System.Collections.Generic.List<System.IntPtr> CreateFunctionPointers()
		{
			System.Collections.Generic.List<System.IntPtr> list = base.CreateFunctionPointers();
			return list;
		}
	}
}
