//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	[System.Flags()]
	public enum NxRaycastBit : uint
	{
		
NX_RAYCAST_SHAPE =  (1<<0),
		
NX_RAYCAST_IMPACT =  (1<<1),
		
NX_RAYCAST_NORMAL =  (1<<2),
		
NX_RAYCAST_FACE_INDEX =  (1<<3),
		
NX_RAYCAST_DISTANCE =  (1<<4),
		
NX_RAYCAST_UV =  (1<<5),
		
NX_RAYCAST_FACE_NORMAL =  (1<<6),
		
NX_RAYCAST_MATERIAL =  (1<<7),
	}
}
