//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	[System.Flags()]
	public enum NxRemoteDebuggerObjectType : uint
	{
		
NX_DBG_OBJECTTYPE_GENERIC =  0,
		
NX_DBG_OBJECTTYPE_ACTOR =  1,
		
NX_DBG_OBJECTTYPE_PLANE =  2,
		
NX_DBG_OBJECTTYPE_BOX =  3,
		
NX_DBG_OBJECTTYPE_SPHERE =  4,
		
NX_DBG_OBJECTTYPE_CAPSULE =  5,
		
NX_DBG_OBJECTTYPE_CYLINDER =  6,
		
NX_DBG_OBJECTTYPE_CONVEX =  7,
		
NX_DBG_OBJECTTYPE_MESH =  8,
		
NX_DBG_OBJECTTYPE_WHEEL =  9,
		
NX_DBG_OBJECTTYPE_JOINT =  10,
		
NX_DBG_OBJECTTYPE_CONTACT =  11,
		
NX_DBG_OBJECTTYPE_BOUNDINGBOX =  12,
		
NX_DBG_OBJECTTYPE_VECTOR =  13,
		
NX_DBG_OBJECTTYPE_CAMERA =  14,
		
NX_DBG_OBJECTTYPE_CLOTH =  15,
		
NX_DBG_OBJECTTYPE_SOFTBODY =  16,
		
NX_DBG_OBJECTTYPE_FLUID = 	17,
	}
}
