//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	public class NxUserTriggerReport : DoxyBindObject
	{
		
		internal NxUserTriggerReport(IntPtr ptr) : 
				base(ptr)
		{
		}
		
		/// <summary>Called when a trigger shape reports a trigger event. </summary>
		/// <param name="triggerShape">is the shape that has been marked as a trigger. </param>
		/// <param name="otherShape">is the shape causing the trigger event. </param>
		/// <param name="status">is the type of trigger event.</param>
		public virtual void onTrigger(NxShape triggerShape, NxShape otherShape, NxShapeFlag status)
		{
			if (doSetFunctionPointers)
			{
				throw new System.NotSupportedException("Cannot call abstract base member");
			}
			NxUserTriggerReport_onTrigger_INVOKE(ClassPointer, doSetFunctionPointers, (triggerShape!=null ? triggerShape.ClassPointer : NullRef), (otherShape!=null ? otherShape.ClassPointer : NullRef), status);
		}
		
		private void onTrigger_virtual(IntPtr triggerShape, IntPtr otherShape, NxShapeFlag status)
		{
			onTrigger(NxShape.GetClass(triggerShape), NxShape.GetClass(otherShape), status);
		}
		
		delegate void onTrigger_0_delegate(IntPtr triggerShape, IntPtr otherShape, NxShapeFlag status);
		
		
		
		
		
		
		private onTrigger_0_delegate onTrigger_0_delegatefield;
		
		#region Imports
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxUserTriggerReport_onTrigger")]
        private extern static void NxUserTriggerReport_onTrigger_INVOKE (HandleRef classPointer, System.Boolean call_explicit, HandleRef triggerShape, HandleRef otherShape, NxShapeFlag status);

		#endregion
		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="new_NxUserTriggerReport")]
        private extern static IntPtr new_NxUserTriggerReport_INVOKE (bool do_override);

		
		protected NxUserTriggerReport() : 
				base(IntPtr.Zero)
		{
			GC.ReRegisterForFinalize(this);
			if ((GetType() != typeof(NxUserTriggerReport)))
			{
				doSetFunctionPointers = true;
				SetPointer(new_NxUserTriggerReport_INVOKE(doSetFunctionPointers));
				System.IntPtr[] pointers = CreateFunctionPointers().ToArray();
				set_pointers_INVOKE(ClassPointer, pointers, pointers.Length);
			}
			else
			{
				SetPointer(new_NxUserTriggerReport_INVOKE(doSetFunctionPointers));
			}
		}
		
		private static System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference> database = new System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference>();
		
		protected override void SetPointer(IntPtr ptr)
		{
			base.SetPointer(ptr);
			database[ptr] = new WeakReference(this);
		}
		
		public override void Dispose()
		{
			database.Remove(ClassPointer.Handle);
			base.Dispose();
		}
		
		public static NxUserTriggerReport GetClass(IntPtr ptr)
		{
			if ((ptr == IntPtr.Zero))
			{
				return null;
			}
			System.WeakReference obj;
			if (database.TryGetValue(ptr, out obj))
			{
				if (obj.IsAlive)
				{
					return ((NxUserTriggerReport)(obj.Target));
				}
			}
			return new NxUserTriggerReport(ptr);
		}
		
		protected override System.Collections.Generic.List<System.IntPtr> CreateFunctionPointers()
		{
			System.Collections.Generic.List<System.IntPtr> list = base.CreateFunctionPointers();
			onTrigger_0_delegatefield = new onTrigger_0_delegate(this.onTrigger_virtual);
			list.Add(Marshal.GetFunctionPointerForDelegate(onTrigger_0_delegatefield));
			return list;
		}
	}
}
