//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007-2008
// Available under the terms of the
// Eclipse Public License with GPL exception
// See enclosed license file for more information
namespace PhysX.NET
{
	using System;
	using System.Runtime.InteropServices;
	
	
	public class NxUserContactReport : DoxyBindObject
	{
		
		internal NxUserContactReport(IntPtr ptr) : 
				base(ptr)
		{
		}
		
		/// <summary></summary>
		/// <param name="pair">The contact pair we are being notified of. See NxContactPair. </param>
		/// <param name="events">Flags raised due to the contact. See NxContactPairFlag.</param>
		public virtual void onContactNotify(NxContactPair pair, uint events)
		{
			if (doSetFunctionPointers)
			{
				throw new System.NotSupportedException("Cannot call abstract base member");
			}
			NxUserContactReport_onContactNotify_INVOKE(ClassPointer, doSetFunctionPointers, (pair!=null ? pair.ClassPointer : NullRef), events);
		}
		
		private void onContactNotify_virtual(IntPtr pair, uint events)
		{
			onContactNotify(NxContactPair.GetClass(pair), events);
		}
		
		delegate void onContactNotify_0_delegate(IntPtr pair, uint events);
		
		
		
		
		
		
		private onContactNotify_0_delegate onContactNotify_0_delegatefield;
		
		#region Imports
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="NxUserContactReport_onContactNotify")]
        private extern static void NxUserContactReport_onContactNotify_INVOKE (HandleRef classPointer, System.Boolean call_explicit, HandleRef pair, System.UInt32 events);

		#endregion
		
        [System.Security.SuppressUnmanagedCodeSecurity()]
        [DllImport(NATIVE_LIBRARY, EntryPoint="new_NxUserContactReport")]
        private extern static IntPtr new_NxUserContactReport_INVOKE (bool do_override);

		
		protected NxUserContactReport() : 
				base(IntPtr.Zero)
		{
			GC.ReRegisterForFinalize(this);
			if ((GetType() != typeof(NxUserContactReport)))
			{
				doSetFunctionPointers = true;
				SetPointer(new_NxUserContactReport_INVOKE(doSetFunctionPointers));
				System.IntPtr[] pointers = CreateFunctionPointers().ToArray();
				set_pointers_INVOKE(ClassPointer, pointers, pointers.Length);
			}
			else
			{
				SetPointer(new_NxUserContactReport_INVOKE(doSetFunctionPointers));
			}
		}
		
		private static System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference> database = new System.Collections.Generic.Dictionary<System.IntPtr, System.WeakReference>();
		
		protected override void SetPointer(IntPtr ptr)
		{
			base.SetPointer(ptr);
			database[ptr] = new WeakReference(this);
		}
		
		public override void Dispose()
		{
			database.Remove(ClassPointer.Handle);
			base.Dispose();
		}
		
		public static NxUserContactReport GetClass(IntPtr ptr)
		{
			if ((ptr == IntPtr.Zero))
			{
				return null;
			}
			System.WeakReference obj;
			if (database.TryGetValue(ptr, out obj))
			{
				if (obj.IsAlive)
				{
					return ((NxUserContactReport)(obj.Target));
				}
			}
			return new NxUserContactReport(ptr);
		}
		
		protected override System.Collections.Generic.List<System.IntPtr> CreateFunctionPointers()
		{
			System.Collections.Generic.List<System.IntPtr> list = base.CreateFunctionPointers();
			onContactNotify_0_delegatefield = new onContactNotify_0_delegate(this.onContactNotify_virtual);
			list.Add(Marshal.GetFunctionPointerForDelegate(onContactNotify_0_delegatefield));
			return list;
		}
	}
}
